---
title: "Tarea_Maria Jose Bu Moreno"
author: "Maria Jose Bu Moreno"
format: html
editor: visual
---


```{r}
# Base de datos "Temp" con las temperaturas ambientes y corporales de Odonata:Zygoptera

Temp <- read.csv("C:/Users/majo_/Curso ECOSUR/Curso ECOSUR/Temp_ejercicios/Temp_ejercicios/Temp.csv")

View(Temp)
head(Temp)

# Cada temperatura corporal es la media de 3 datos toraxicos

```

```{r}
# Paquetes utilizados

library(ggplot2)
library("performance")
library("effects")
library(model_BT)

```

```{r}

# Grafica de temperatura corporal versus temperatura ambiente en Odonata:Zygoptera

ggplot(Temp, aes(x=Tambiental, y=Tcorporal)) +
  geom_point(pch = 23, bg = "darkred", cex = 5)+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)+
  labs(title = "Incidencia de la temperatura ambiente con la temperatura corporal de Zygoptera") +
  xlab("Temperatura Ambiental") +
  ylab("Temperatura Corporal") +
  theme_light()+
scale_color_grey()

```

```{r}

model_BT<-lm(Tcorporal~Tambiental,data=Temp)

summary(model_BT)


```
